### ISSUE TITLE
GRID_DEPTH isn't working

### ISSUE THREAD

**Issue by ruskvm** [assassinen/grid_client#1]
The bot don't stop if the grid_depth is reached.

**Comment by assassinen** [comment]
show logs

**Comment by ruskvm** [comment]
it ignores the grid_depth variable. There is no error in the logs.

**Comment by assassinen** [comment]
no logs, no solution

**Comment by ruskvm** [comment]
![settings](https://user-images.githubusercontent.com/54377403/69873707-599e0780-12b9-11ea-82ce-57608160dd45.JPG)
![log](https://user-images.githubusercontent.com/54377403/69873710-5acf3480-12b9-11ea-9a07-cb6b4a063d0c.JPG)

**Comment by assassinen** [comment]
what is the orderqty for grid?

![image](https://user-images.githubusercontent.com/22366835/69876035-a4c31500-12cf-11ea-8e30-bd22b4c0ddc7.png)

**Comment by assassinen** [comment]
Yes, there is a problem.

**Comment by ruskvm** [comment]
How can I fix it ?

**Comment by assassinen** [comment]
find the reason and fix it

**Comment by assassinen** [comment]
fixed
to update, use docker-compose pull
